### PR TITLE
Allow TOC in any .md file

### PR DESCRIPTION
**Pull request by yajo**
Doesn't make much sense to restrict this just to README, isn't it?

### CODE REVIEW

**Comment by yajo** [comment]
It seems this fails if there are several .md files. Maybe we need to add also `require_serial: true`?

**Comment by Lucas-C** [comment]
You can override this `files` value in `.pre-commit-config.yaml` !
_cf._ https://pre-commit.com/#plugins
No need to change the default value of this hook I think

**Comment by Lucas-C** [comment]
Considering my answer, unless you have anything to add @Yajo, I will close this PR.

**Comment by yajo** [comment]
But why can't that be the default?

**Comment by Lucas-C** [comment]
Alright, all things considered, I'm merging this.

Thank you for your contribution !

**Pull request merged**
